@E_Commerce_Web_Server_HostAddress = http://localhost:5179

GET {{E_Commerce_Web_Server_HostAddress}}
Accept: application/json

###
GET {{E_Commerce_Web_Server_HostAddress}}/api/categories
Accept: application/json

###
POST {{E_Commerce_Web_Server_HostAddress}}/api/categories
Content-Type: application/json

{
    "name" : "",
    "description" : "All mechanical items"
}

